export const WALK_IN_SHOWER = "WALK_IN_SHOWER";
export const SHOWER_CABIN = "SHOWER_CABIN";
export const SHOWER_DOOR = "SHOWER_DOOR";

export const BUILT_IN_BATH = "BUILT_IN_BATH";
export const FREE_STANDING_BATH = "FREE_STANDING_BATH";
export const BATH_SHOWER_COMBINATION = "BATH_SHOWER_COMBINATION";

export const DEMOLITION_WORKS = "DEMOLITION_WORKS";
export const CONSTRUCTION_CONTAINER = "CONSTRUCTION_CONTAINER";
export const NO_DEMOLITION_WORKS = "NO_DEMOLITION_WORKS";

export const BATHROOM_FURNITURE = "BATHROOM_FURNITURE";
export const NO_BATHROOM_FURNITURE = "NO_BATHROOM_FURNITURE";

export const WARM_FLOOR_LESS_THAN_5 = "WARM_FLOOR_LESS_THAN_5";
export const WARM_FLOOR_MORE_THAN_5 = "WARM_FLOOR_MORE_THAN_5";
export const WALL_HEATER = "WALL_HEATER";
export const NO_HEATING = "NO_HEATING";

export const ELECTRICITY_MAX_5 = "ELECTRICITY_MAX_5";
export const ELECTRICITY_MAX_7 = "ELECTRICITY_MAX_7";
export const NO_ELECTRICITY = "NO_ELECTRICITY";

export const PLUMBER_MAX_3 = "PLUMBER_MAX_3";
export const PLUMBER_MAX_6 = "PLUMBER_MAX_6";
export const PLUMBER_MAX_8 = "PLUMBER_MAX_8";
export const NO_PLUMBER = "NO_PLUMBER";

export const WC = "WC";
export const WC_SHOWER = "WC_SHOWER";
export const NO_WC = "NO_WC";

export const BASIC_TILES = "BASIC_TILES";
export const LUX_TILES = "LUX_TILES";
export const NO_TILES = "NO_TILES";


export const TILES_SELECTED = [
  BASIC_TILES, LUX_TILES
];


export const CALCULATION_FORM = "CALCULATION_FORM";

// export const SHOWER_TYPE_ACTIONS = [WALK_IN_SHOWER, SHOWER_CABIN, SHOWER_DOOR];
// export const BATH_TYPE_ACTIONS = [BUILT_IN_BATH, FREE_STANDING_BATH, BATH_SHOWER_COMBINATION];


// Local Storage constants

export const LOCAL_USER_BUDGET_DATA = "LOCAL_USER_BUDGET_DATA";

export const PHONE_NUMBER = {
  toCall: "31633678141",
  toShow: "+31 (0)63 367 8141"
}
